name: CI - DevSecOps Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  checkout-test:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vérification
        run: echo "OK"
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sca-backend:
    name: Composer Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Composer Install
        working-directory: backend
        run: composer install --no-interaction --no-progress
      - name: Composer Audit
        working-directory: backend
        run: composer audit
  sca-frontend:
    name: Npm Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Npm Install
        working-directory: frontend
        run: npm install
      - name: Npm Audit
        working-directory: frontend
        run: npm audit --audit-level=high
  container-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Backend
        run: docker build -t afrikraga-demo-backend -f Dockerfile.backend backend
      - name: Build Frontend
        run: docker build -t afrikraga-demo-frontend -f Dockerfile.frontend frontend
      - name: Trivy Scan - Backend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: afrikraga-demo-backend
          severity: CRITICAL
          exit-code: '1'
          trivyignores: .trivyignore
      - name: Trivy Scan - Frontend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: afrikraga-demo-frontend
          severity: CRITICAL
          exit-code: '1'
          trivyignores: .trivyignore
